[Rev]
ini_rev = "1.0.0"
main_rev = "1.0.0"

[Name]
Device_Name	= "HND.BFS02"
# 场地编码		HND/NRT/KIX
# 客户端编码		SRF/DRF/BFS	单机/双机/狂扫
# 预留大屏、监控、非控制设备等
# Device_Type = "Host/Client"
# 主从类型 暂时只有双机线存在

[Network]
# 本机IP，用于显示、环路测试等，甚至可以设置127.0.0.1
# 当前该设置无程序使用
# Local_IP = "127.0.0.1"

# Redis DB
Redis_IP="127.0.0.1"
Redis_Port="6379"
Redis_DB="0"

# 扫描平台
# 当前IP仅用于连接HIKCamera服务器
Barcode_Reading_IP = "127.0.0.1"
# 扫描平台端口
Barcode_Reading_Port = 2000

# 使用Snap 7 连接 PLC时使用的IP及端口
# ----------------------------------------
# BFS01使用 '192.168.18.150'
# PLC_server_ip = '192.168.18.150'
# ----------------------------------------
# BFS02使用 '192.168.18.160'
PLC_Server_IP = '192.168.18.160'
# ----------------------------------------
PLC_Server_Port = 3000

# dss服务器地址
DSS_IP = "192.168.18.130"
DSS_Port = 7979

[DSS_Push]
# dss推送服务开关，1为开启，0为关闭
MODE = 0

[Log_Config]
# 日志配置
Log_Level = "DEBUG"
Log_Filename = "log/BFS_main.log"
Log_Size = 10*1024*1024
Log_Count = 100
[Trace]
HIKCamera_EnableTrace = "Yes"
PLC_EnableTrace = "Yes"

[PLC_Config]
# 程序中使用的DB块
DB3_size = 3
# PLC控制的输送机高速、低速状态下，每个PLC程序cycletime运行的mm数
# 高速400mm/s,ct=100ms, speed_H= 400*ct/1000=40mm/ct
ini_speed_H = 40
ini_speed_L = 20
# CV03的总长度
ini_conv_length = 3000
# 海康在CV02上输出信号的位置，按照CV02 = 2400mm 计算，该位置到CV03的距离
# 影响延时参数的计算，并可能导致包裹错误流出。
# 当未补码包裹距离CV04过远时，可增加此参数，为补码争取更多时间
ini_HIKOut_position = 1600

# 用于修正启停参数以及其他因素，对停止位置的影响的
# 作用方向为负方向，即该数字越大，停止的越早；最小为零
ini_stop_position_offset = 4
; 空闲超时时间（单位：秒）
ini_idle_timeout = 1800

# 程序启动时，是否自动启动输送机
StartConv = True

# 允许的 Barcode 正在表达式
[Barcode]
re_exp_01 = "(?=^[0-9a-zA-Z]+$)(?=^(EXK).*)(?=.*(J)$)(^.{12,12}$)"
re_exp_02 = "(?=^[0-9a-zA-Z]+$)(?=^(EFS).*)(^.{13,13}$)"
#re_exp_01 = "(?=^[0-9a-zA-Z]+$)(?=^(HY).*)(^.{11,11}$)"
#re_exp_02 = "(?=^\d+$)(^.{12,12}$)"

[Image_Source_Path]
AIRead_path = "D:\\Image\\RGBDPano\\AlRead"
ErrRead_path = "D:\\Image\\RGBDPano\\ErrRead"
NoRead_path = "D:\\Image\\RGBDPano\\NoRead"

[Image_Target_Path]
AITarget_path = "D:\\TEST\\Image\\RGBDPano\\AlRead"
ErrTarget_path = "D:\\TEST\\Image\\RGBDPano\\ErrRead"
NoTarget_path = "D:\\TEST\\Image\\RGBDPano\\NoRead"

[CycleTime]
prc_monitor_cycletime = 50
prc_monitor_expiretime = 15000
prc_monitor_healthytime= 200

prc_HIKCamera_cycletime = 100
prc_HIKCamera_expiretime = 5000
prc_HIKCamera_healthytime= 2000

prc_PLC_cycletime = 100
prc_PLC_expiretime = 999000
prc_PLC_healthytime= 250

prc_stmHIKC_cycletime = 200
prc_stmHIKC_expiretime = 5000
prc_stmHIKC_healthytime= 2000

prc_stmManualScan_cycletime = 300
prc_stmManualScan_expiretime = 5000
prc_stmManualScan_healthytime= 2000

prc_stmReadingConfirm_cycletime = 300
prc_stmReadingConfirm_expiretime = 5000
prc_stmReadingConfirm_healthytime= 2000

prc_stmReadingConfirmdss_cycletime = 300
prc_stmReadingConfirmdss_expiretime = 990000
prc_stmReadingConfirmdss_healthytime= 2000

prc_BarcodeCheck_cycletime = 200
prc_BarcodeCheck_expiretime = 5000
prc_BarcodeCheck_healthytime= 2000

prc_stimHIKCfile_cycletime = 50
prc_stimHIKCfile_expiretime = 999000
prc_stimHIKCfile_healthytime= 2000

[find_maxnumber]
max_number = 30

; [Sound]
; reading_gr = 'media/80_scan_gr.mp3'
; reading_nr = 'media/10-scan_nr.mp3'
; reading_mr = 'media/10-scan_nr.mp3'
; check_ng ='media/99_ALARM.mp3'
; ms_barcode_reject='media/00_barcode_reject.mp3'
; ms_barcode_exist='media/04_barcode_exist.mp3'
; ms_barcode_rescan_accept='media/01_barcode_rescan_accept.mp3'


# 本机连接的PLC IP
# PLC_IP = "xx.xx.xx.xx"
# 机架号
# PLC_Rack = 0
# 槽号
# PLC_Slot = 1

# RFID Tunnel IP
# RFID_IP_01 = "xx.xx.xx.xx"
# RFID_IP_02 = "xx.xx.xx.xx"

# Scanner  IP
# Camera_IP_01 = "xx.xx.xx.xx"
# Camera_IP_02 = "xx.xx.xx.xx"
# RGBD_IP = "xx.xx.xx.xx"
# 本地数据库
# LDB_Server = "xx.xx.xx.xx"
# LDB_Port = 3306
# LDB_User = "root"
# LDB_Pwd = "root"
# 设备注册服务器
# DRS_IP = xx.xx.xx.xx
# 云端数据库
# CDB_Server = xx.xx.xx.xx
# CDB_Port = 3306
# CDB_User = "root"
# CDB_Pwd	= "root"

;[Default_Config]
# 默认配置